/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FormItemVant: typeof import('./../components/dynamicForm/FormItemVant.vue')['default']
    FormLabelVant: typeof import('./../components/dynamicForm/FormLabelVant.vue')['default']
    FormLabelVantCell: typeof import('./../components/dynamicForm/FormLabelVantCell.vue')['default']
    FormLabelVantField: typeof import('./../components/dynamicForm/FormLabelVantField.vue')['default']
    FormLabelVantGroup: typeof import('./../components/dynamicForm/FormLabelVantGroup.vue')['default']
    Index: typeof import('./../components/chart/Index.vue')['default']
    NavBar: typeof import('./../components/layout/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./../components/layout/TabBar.vue')['default']
  }
}
